### ISSUE TITLE
alternative logo idea

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/artwork#2]
Using your logo for inspiration, came up with a slightly more minimalist logo:
- using the JavaScript tradition of a yellow/black color scheme.
- some clipart I found based on your idea of a document with commit messages in it.

![conventional-changelog](https://cloud.githubusercontent.com/assets/194609/16405243/eac7cefe-3cba-11e6-9367-d3501caeaf34.png)

I'm also perfectly fine sticking with the existing logo, just thought I'd throw my own idea into the running.

**Comment by stevemao** [comment]
LGTM :)

**Comment by bcoe** [comment]
@stevemao I owe you vector art and and pngs for this logo! I'm going to go ahead and land it, and see if we like how it looks for our icon.

**Comment by stevemao** [comment]
the artist I found doesn't do logos for software but anime style. The previous logo looks better if the size is big enough.
I think the new logo here looks better as an icon :)

**Comment by bcoe** [comment]
@stevemao gotcha, maybe we can get them slightly closer to the same look; and use them both in different contexts.

**Comment by stevemao** [comment]
Sounds good :) cc @kazupon @Tapppi @tomchentw

**Comment by kazupon** [comment]
LGTM :)

**Comment by Tapppi** [comment]
Awesome, SGTM!

**Comment by tomchentw** [comment]
This looks great! Awesome work!

**Comment by stevemao** [comment]
@bcoe Can you commit the vector art here?

**Comment by bcoe** [comment]
@stevemao 👍 will get it checked in this weekend.

**Comment by hutson** [comment]
@bcoe when you have the opportunity, could you please commit the SVG? I'd like to work on setting it up across all repositories within the `conventional-changelog` org.
